In [2]:
import numpy as np
import time
import sys

In [3]:
py_list = range(1000) # creaing a python list with 1000 elements 
print(sys.getsizeof(5) * len(py_list)) # printing size of the list = size of 1 number * len of the list

28000


In [4]:
np_array = np.arange(1000) # create numpy array [0, 1, 2, ..., 999] similar to range() in native python
print(np_array.itemsize * np_array.size) # printing size of the numpy array (to compare size with python list)

4000


In [5]:
# test native python list
SIZE = 1000000

list1 = range(SIZE)
list2 = range(SIZE)

start = time.time()
result = [(x + y) for x,y in zip(list1, list2)] # adding 2 list
print("python list took: ", (time.time() - start)* 1000 ,"ms")

python list took:  75.01435279846191 ms


In [6]:
np_arr1 = np.arange(SIZE)
np_arr2 = np.arange(SIZE)

start = time.time()
result = np_arr1 + np_arr2 # more optimize: adding 2 numpy array
print("numpy array took: ", (time.time() - start)*1000, "ms")

numpy array took:  14.000177383422852 ms


In [8]:
a = np.array([1,2,3])

In [9]:
a = np.array([
    [1, 2], [3, 4], [5, 6]
])

In [10]:
a.ndim

2

In [13]:
print(a.itemsize)
print(a.dtype)
# integer --> itemsize is 4 bytes

4
int32


In [14]:
a = np.array([
    [1, 2], [3, 4], [5, 6]
], dtype=np.float64)

dtype('float64')

In [21]:
print(a.itemsize)
print(a.dtype)
print(a) # since it's float so it will output "1., 2."
print(a.size) # print total elements (deepest)
print(len(a)) # print  total elements (outer most)
print(a.shape)

8
float64
[[1. 2.]
 [3. 4.]
 [5. 6.]]
6
3
(3, 2)


In [22]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
numbers = np.linspace(0, 5)
print(numbers)

# the default number of results is set to 50, and equally devided 
# (don't have to specify stepsize like the function np.arange())

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [43]:
# however we are able to change this value
# endpoint = false will eliminate the last value
# retstep = True to get step size (equally divided)
numbers = np.linspace(0, 5, num=20, endpoint=False, retstep=True)
print(numbers)

(array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75]), 0.25)


In [44]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [47]:
a.reshape((6, 1))

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [48]:
# flatten to one dimension
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [50]:
print(a.min())
print(a.max())
print(a.sum())

1.0
6.0
21.0


In [54]:
print(a)
print("-------------")
print("tinh theo chieu doc: ", a.sum(axis=0))
print("tinh theo chieu ngang: ", a.sum(axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]]
-------------
tinh theo chieu doc:  [ 9. 12.]
tinh theo chieu ngang:  [ 3.  7. 11.]


In [55]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [57]:
# standard deviation: of the array

# Phương sai và Độ lệch chuẩn (Variance & Standard Deviation)
# Độ lệch chuẩn là thước đo độ phân tán dữ liệu (measure how spread out numbers are)
# phương sai là : 
# lấy từng point dữ liệu trừ đi cho giá trị trung bình (Mean) và bình phương lên (squared difference)
# rồi lấy giá trị average của các squared difference

print(np.std(a))
print(np.sqrt(np.var(a))) # standard deviation = square root of Variance

1.707825127659933
1.707825127659933


In [58]:
# converting a python list to a numpy array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [59]:
np.full((2, 2), 3.5)

array([[3.5, 3.5],
       [3.5, 3.5]])

In [62]:
np.full((2, 2), [5, 6])

array([[5, 6],
       [5, 6]])

In [68]:
## seed
np.random.seed(42)
np.random.random((4, 4))

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [70]:
np.random.seed(42)
np.random.random((4, 4))

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [71]:
mean = 0
standardDeviation = 1
np.random.normal(mean, standardDeviation, (3, 4))

array([[ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819]])

In [72]:
np.random.randint(0, 10, (4, 5))

array([[8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3],
       [8, 1, 9, 8, 9],
       [4, 1, 3, 6, 7]])

In [74]:
np.random.rand(2, 2)

array([[0.04522729, 0.32533033],
       [0.38867729, 0.27134903]])

In [76]:
# array indexing and slicing

x1 = np.random.randint(20, size=6)
x1

array([ 8,  0, 11,  7, 10, 18])

In [78]:
# multi dimensional
x1 = np.random.randint(20, size=(3, 4))
x1

array([[11,  1,  0, 15],
       [ 4,  2, 11,  7],
       [ 2,  0,  2,  4]])

In [83]:
grid = np.arange(6)
grid.shape

(6,)

In [92]:
x = grid.reshape((1,6))
x

array([[0, 1, 2, 3, 4, 5]])

In [93]:
print(grid.shape)
print(x.shape)

(6,)
(1, 6)


In [95]:
grid = grid.reshape((2, 3))
grid

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
# concatinate numpy arrays
np.concatenate((grid, grid)) # default axis = 0, được nối theo hướng của trục axis = 0 --> vertical stack

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [99]:
np.concatenate((grid, grid), axis=1) # horizontal stack

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [101]:
# vstack -- vertical stack
np.vstack((grid, grid))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [106]:
# hstack -- horizontal stack
testY = np.array([[13], 
                  [40]])

np.hstack((grid, testY))

array([[ 0,  1,  2, 13],
       [ 3,  4,  5, 40]])

In [108]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
np.split(x, [4, 8])

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([8, 9])]

In [109]:
x1, x2, x3 = np.split(x, [4, 8])

In [110]:
x1

array([0, 1, 2, 3])

In [111]:
x2

array([4, 5, 6, 7])

In [112]:
x3

array([8, 9])

In [114]:
# broadcasting and vectorize operation

a = np.arange(0, 3)
a

array([0, 1, 2])

In [115]:
a + 5 # broad casting
# it will create an array of 3 elements [5, 5, 5] to match the size of the array a

array([5, 6, 7])

In [116]:
massive_arr = np.random.random(10000)
%timeit sum(massive_arr) # python built-in function sum

483 µs ± 5.66 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [117]:
%timeit np.sum(massive_arr)

5.09 µs ± 182 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [118]:
# sorting array

In [120]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size=(4, 6))

In [121]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [122]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [123]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [124]:
# Linear Algebra

In [125]:
import numpy as np

In [126]:
np.random.seed(42)

sales_arr = np.random.randint(20, size=(5, 3))
sales_arr

array([[ 6, 19, 14],
       [10,  7,  6],
       [18, 10, 10],
       [ 3,  7,  2],
       [ 1, 11,  5]])

In [127]:
import pandas as pd

In [130]:
weekly_sales = pd.DataFrame(sales_arr, index=['mon', 'tue', 'wed','thu','fri'],
                                        columns=['butter1', 'butter2', 'butter3'])

weekly_sales

butter1  butter2  butter3
mon        6       19       14
tue       10        7        6
wed       18       10       10
thu        3        7        2
fri        1       11        5

In [136]:
prices_of_butter = np.array([10, 8, 2])
print(prices_of_butter.shape)
prices_of_butter = pd.DataFrame(prices_of_butter.reshape(1, 3), index=['prices'], columns=['butter1', 'butter2', 'butter3'])
prices_of_butter

(3,)


butter1  butter2  butter3
prices       10        8        2

In [138]:
# watching both shapes, it's hard to use the DOT PRODUCT
# so that we need to transpose it
print(weekly_sales.shape)
print(prices_of_butter.shape)
print(prices_of_butter.T)

(5, 3)
(1, 3)
         prices
butter1      10
butter2       8
butter3       2


In [140]:
total_prices_each_day = weekly_sales.dot(prices_of_butter.T)
total_prices_each_day

prices
mon     240
tue     168
wed     280
thu      90
fri     108

In [144]:
from IPython.display import display

In [145]:


# add column to dataframe
weekly_sales['total_price'] = total_prices_each_day
display(prices_of_butter)
display(weekly_sales)

butter1  butter2  butter3
prices       10        8        2

butter1  butter2  butter3  total_price
mon        6       19       14          240
tue       10        7        6          168
wed       18       10       10          280
thu        3        7        2           90
fri        1       11        5          108