In [2]:
from distutils.command.config import config
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [3]:
import numpy as np

m_arr = [0,1,2,3,4,5,6,7,8]
m_arr = np.array(m_arr).reshape((3, 3))
print(m_arr)

# np.random.permutation(m_arr)
np.random.permutation(5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([4, 3, 0, 2, 1])

In [4]:
import pandas as pd

mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]

df = pd.DataFrame(mydict)
df

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [5]:
df.iloc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

In [6]:
df.iloc[[0]]

a  b  c  d
0  1  2  3  4

In [7]:
df.iloc[[0, 1, 2]]

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [8]:
df.iloc[[0, 1, 2], [1]]

b
0     2
1   200
2  2000

In [9]:
df_with_id = df.reset_index() # add index column
df_with_id

index     a     b     c     d
0      0     1     2     3     4
1      1   100   200   300   400
2      2  1000  2000  3000  4000

In [10]:
df_with_id['index'] = df_with_id['a'] * 2
df_with_id

index     a     b     c     d
0      2     1     2     3     4
1    200   100   200   300   400
2   2000  1000  2000  3000  4000

In [11]:
df[['a', 'b', 'c']]

a     b     c
0     1     2     3
1   100   200   300
2  1000  2000  3000

In [12]:
df[['d']]

d
0     4
1   400
2  4000

In [13]:
df['d']

0       4
1     400
2    4000
Name: d, dtype: int64

In [16]:
df.iloc[:2]

a    b    c    d
0    1    2    3    4
1  100  200  300  400

In [5]:
import numpy as np

a = np.array([
    [1, 2, 3], 
    [1, 2, 3], 
    [1, 2, 3]
])

b = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [4, 5, 6]
])

np.vstack((a,b))
# vstack works when 2 arrays have the same amount of columns


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [8]:
c = np.array([
    [4, 5, 6, 7],
    [4, 5, 6, 7],
    [4, 5, 6, 7]
])

np.vstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [9]:
np.hstack((a,b))
# vstack works when 2 arrays have the same amount of rows

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [11]:
np.hstack((a,c))

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [12]:
d = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [4, 5, 6],
    [4, 5, 6]
])

np.hstack((a,d))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4